development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: rediss://:paa9e6611a20efddca29a54385e27d921bdba39d0d6d19089ff4ca454f60020a7@ec2-54-197-136-218.compute-1.amazonaws.com:25370
  channel_prefix: ortho_doc_instrument_manual_api_production
